import type { Perfil, Proyecto, Ticket } from "./types"

export const mockPerfiles: Perfil[] = [
  {
    id: "1",
    nombre: "Carlos Mendoza",
    email: "carlos@hunterstrack.com",
    rol: "lider_ti",
  },
  {
    id: "2",
    nombre: "María García",
    email: "maria@hunterstrack.com",
    rol: "admin",
  },
  {
    id: "3",
    nombre: "Juan Pérez",
    email: "juan@hunterstrack.com",
    rol: "developer",
  },
  {
    id: "4",
    nombre: "Ana López",
    email: "ana@hunterstrack.com",
    rol: "developer",
  },
  {
    id: "5",
    nombre: "Roberto Sánchez",
    email: "roberto@hunterstrack.com",
    rol: "staff",
  },
  {
    id: "6",
    nombre: "Laura Martínez",
    email: "laura@hunterstrack.com",
    rol: "staff",
  },
]

export const mockProyectos: Proyecto[] = [
  {
    id: "p1",
    nombre: "Portal de Clientes v2.0",
    descripcion: "Rediseño completo del portal de clientes con nuevas funcionalidades",
    estado: "en_desarrollo",
    progreso: 75,
    aprobacion_ti: true,
    aprobacion_negocio: true,
    fecha_creacion: "2024-01-15",
    fecha_actualizacion: "2024-03-10",
  },
  {
    id: "p2",
    nombre: "Sistema de Inventario",
    descripcion: "Implementación de sistema de gestión de inventario en tiempo real",
    estado: "en_desarrollo",
    progreso: 45,
    aprobacion_ti: true,
    aprobacion_negocio: false,
    fecha_creacion: "2024-02-01",
    fecha_actualizacion: "2024-03-08",
  },
  {
    id: "p3",
    nombre: "App Móvil Vendedores",
    descripcion: "Aplicación móvil para equipo de ventas en campo",
    estado: "propuesta",
    progreso: 10,
    aprobacion_ti: false,
    aprobacion_negocio: false,
    fecha_creacion: "2024-03-01",
    fecha_actualizacion: "2024-03-05",
  },
  {
    id: "p4",
    nombre: "Dashboard Analytics",
    descripcion: "Panel de análisis y métricas de negocio con IA",
    estado: "en_desarrollo",
    progreso: 90,
    aprobacion_ti: true,
    aprobacion_negocio: true,
    fecha_creacion: "2023-11-20",
    fecha_actualizacion: "2024-03-12",
  },
]

export const mockTickets: Ticket[] = [
  {
    id: "t1",
    titulo: "Error en login de usuarios",
    descripcion: "Los usuarios reportan problemas al iniciar sesión después de las 6pm",
    tipo: "soporte",
    estado: "en_revision",
    solicitante_id: "5",
    solicitante_nombre: "Roberto Sánchez",
    fecha_creacion: "2024-03-10",
    fecha_actualizacion: "2024-03-10",
  },
  {
    id: "t2",
    titulo: "Actualizar módulo de reportes",
    descripcion: "Se requiere agregar nuevos filtros al módulo de reportes financieros",
    tipo: "mantenimiento",
    estado: "aprobado",
    solicitante_id: "6",
    solicitante_nombre: "Laura Martínez",
    developer_id: "3",
    developer_nombre: "Juan Pérez",
    fecha_creacion: "2024-03-08",
    fecha_actualizacion: "2024-03-09",
  },
  {
    id: "t3",
    titulo: "Lentitud en carga de dashboard",
    descripcion: "El dashboard principal tarda más de 10 segundos en cargar",
    tipo: "soporte",
    estado: "en_progreso",
    solicitante_id: "5",
    solicitante_nombre: "Roberto Sánchez",
    developer_id: "4",
    developer_nombre: "Ana López",
    proyecto_id: "p4",
    fecha_creacion: "2024-03-05",
    fecha_actualizacion: "2024-03-11",
  },
  {
    id: "t4",
    titulo: "Migración de base de datos",
    descripcion: "Necesario migrar datos históricos al nuevo servidor",
    tipo: "mantenimiento",
    estado: "corregido",
    solicitante_id: "6",
    solicitante_nombre: "Laura Martínez",
    developer_id: "3",
    developer_nombre: "Juan Pérez",
    fecha_creacion: "2024-02-28",
    fecha_actualizacion: "2024-03-07",
  },
  {
    id: "t5",
    titulo: "Nuevo formulario de contacto",
    descripcion: "Implementar formulario de contacto con validaciones",
    tipo: "mantenimiento",
    estado: "en_revision",
    solicitante_id: "5",
    solicitante_nombre: "Roberto Sánchez",
    fecha_creacion: "2024-03-12",
    fecha_actualizacion: "2024-03-12",
  },
]

export const getDevelopers = () => mockPerfiles.filter((p) => p.rol === "developer")
